package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name="subjects"
    
)
public class Subjects  implements java.io.Serializable {


     private Integer subjectId;
     private Classes classes;
     private String subjectName;
     private int totalMarks;
     private int passingMarks;
     private int isOld;
     private Integer sequenceNo;
     private String remarks;
     private Set<ExamResult> examResults = new HashSet<ExamResult>(0);

    public Subjects() {
    }

	
    public Subjects(Classes classes, String subjectName, int totalMarks, int passingMarks, int isOld, String remarks) {
        this.classes = classes;
        this.subjectName = subjectName;
        this.totalMarks = totalMarks;
        this.passingMarks = passingMarks;
        this.isOld = isOld;
        this.remarks = remarks;
    }
    public Subjects(Classes classes, String subjectName, int totalMarks, int passingMarks, int isOld, Integer sequenceNo, String remarks, Set examResults) {
       this.classes = classes;
       this.subjectName = subjectName;
       this.totalMarks = totalMarks;
       this.passingMarks = passingMarks;
       this.isOld = isOld;
       this.sequenceNo = sequenceNo;
       this.remarks = remarks;
       this.examResults = examResults;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="subject_id", unique=true, nullable=false)
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    
    @Column(name="subject_name", nullable=false, length=100)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    
    @Column(name="total_marks", nullable=false)
    public int getTotalMarks() {
        return this.totalMarks;
    }
    
    public void setTotalMarks(int totalMarks) {
        this.totalMarks = totalMarks;
    }
    
    @Column(name="passing_marks", nullable=false)
    public int getPassingMarks() {
        return this.passingMarks;
    }
    
    public void setPassingMarks(int passingMarks) {
        this.passingMarks = passingMarks;
    }
    
    @Column(name="is_old", nullable=false)
    public int getIsOld() {
        return this.isOld;
    }
    
    public void setIsOld(int isOld) {
        this.isOld = isOld;
    }
    
    @Column(name="sequence_no")
    public Integer getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="remarks", nullable=false, length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subjects")
    public Set<ExamResult> getExamResults() {
        return this.examResults;
    }
    
    public void setExamResults(Set examResults) {
        this.examResults = examResults;
    }

@Override
    public String toString() {
        return subjectName; //To change body of generated methods, choose Tools | Templates.
    }



}


