package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpAccounts generated by hbm2java
 */
@Entity
@Table(name="emp_accounts"
    
)
public class EmpAccounts  implements java.io.Serializable {


     private Integer empAccountsId;
     private Campus campus;
     private EmpAccountCategory empAccountCategory;
     private String name;
     private String father;
     private String surname;
     private String contact;
     private String address;
     private String post;
     private Date joiningDate;
     private Date birthDate;
     private String gender;
     private Integer basicSalary;
     private Date leavingDate;
     private String remarks;
     private Integer travelingAllowance;
     private Integer otherAllowance;
     private Integer totalAmount;
     private String nic;
     private String refLetter;
     private Integer headAllowance;
     private Integer coordinateAllowace;
     private Integer ctAllowance;
     private Integer medicalAllowance;
     private Integer fiveYearAllowance;
     private String staffId;
     private String bankAccountNo;
     private Integer orderNo;
     private Boolean deleted;
     private Set<EmpAccountAttachment> empAccountAttachments = new HashSet<EmpAccountAttachment>(0);
     private Set<Designation> designations = new HashSet<Designation>(0);
     private Set<Salary> salaries = new HashSet<Salary>(0);
     private Set<EmpCertificateIssue> empCertificateIssues = new HashSet<EmpCertificateIssue>(0);

    public EmpAccounts() {
    }

	
    public EmpAccounts(Campus campus, EmpAccountCategory empAccountCategory, String name, String father) {
        this.campus = campus;
        this.empAccountCategory = empAccountCategory;
        this.name = name;
        this.father = father;
    }
    public EmpAccounts(Campus campus, EmpAccountCategory empAccountCategory, String name, String father, String surname, String contact, String address, String post, Date joiningDate, Date birthDate, String gender, Integer basicSalary, Date leavingDate, String remarks, Integer travelingAllowance, Integer otherAllowance, Integer totalAmount, String nic, String refLetter, Integer headAllowance, Integer coordinateAllowace, Integer ctAllowance, Integer medicalAllowance, Integer fiveYearAllowance, Set empAccountAttachments, Set designations, Set salaries, Set empCertificateIssues) {
       this.campus = campus;
       this.empAccountCategory = empAccountCategory;
       this.name = name;
       this.father = father;
       this.surname = surname;
       this.contact = contact;
       this.address = address;
       this.post = post;
       this.joiningDate = joiningDate;
       this.birthDate = birthDate;
       this.gender = gender;
       this.basicSalary = basicSalary;
       this.leavingDate = leavingDate;
       this.remarks = remarks;
       this.travelingAllowance = travelingAllowance;
       this.otherAllowance = otherAllowance;
       this.totalAmount = totalAmount;
       this.nic = nic;
       this.refLetter = refLetter;
       this.headAllowance = headAllowance;
       this.coordinateAllowace = coordinateAllowace;
       this.ctAllowance = ctAllowance;
       this.medicalAllowance = medicalAllowance;
       this.fiveYearAllowance = fiveYearAllowance;
       this.empAccountAttachments = empAccountAttachments;
       this.designations = designations;
       this.salaries = salaries;
       this.empCertificateIssues = empCertificateIssues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="emp_accounts_id", unique=true, nullable=false)
    public Integer getEmpAccountsId() {
        return this.empAccountsId;
    }
    
    public void setEmpAccountsId(Integer empAccountsId) {
        this.empAccountsId = empAccountsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campus_id", nullable=false)
    public Campus getCampus() {
        return this.campus;
    }
    
    public void setCampus(Campus campus) {
        this.campus = campus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_account_category_id", nullable=false)
    public EmpAccountCategory getEmpAccountCategory() {
        return this.empAccountCategory;
    }
    
    public void setEmpAccountCategory(EmpAccountCategory empAccountCategory) {
        this.empAccountCategory = empAccountCategory;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="father", nullable=false, length=100)
    public String getFather() {
        return this.father;
    }
    
    public void setFather(String father) {
        this.father = father;
    }
    
    @Column(name="surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="contact", length=50)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="post", length=100)
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="joining_date", length=10)
    public Date getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    
    @Column(name="gender", length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="basic_salary")
    public Integer getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(Integer basicSalary) {
        this.basicSalary = basicSalary;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="leaving_date", length=10)
    public Date getLeavingDate() {
        return this.leavingDate;
    }
    
    public void setLeavingDate(Date leavingDate) {
        this.leavingDate = leavingDate;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="traveling_allowance")
    public Integer getTravelingAllowance() {
        return this.travelingAllowance;
    }
    
    public void setTravelingAllowance(Integer travelingAllowance) {
        this.travelingAllowance = travelingAllowance;
    }
    
    @Column(name="other_allowance")
    public Integer getOtherAllowance() {
        return this.otherAllowance;
    }
    
    public void setOtherAllowance(Integer otherAllowance) {
        this.otherAllowance = otherAllowance;
    }
    
    @Column(name="total_amount")
    public Integer getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="nic", length=45)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    
    @Column(name="ref_letter", length=100)
    public String getRefLetter() {
        return this.refLetter;
    }
    
    public void setRefLetter(String refLetter) {
        this.refLetter = refLetter;
    }
    
    @Column(name="head_allowance")
    public Integer getHeadAllowance() {
        return this.headAllowance;
    }
    
    public void setHeadAllowance(Integer headAllowance) {
        this.headAllowance = headAllowance;
    }
    
    @Column(name="coordinate_allowace")
    public Integer getCoordinateAllowace() {
        return this.coordinateAllowace;
    }
    
    public void setCoordinateAllowace(Integer coordinateAllowace) {
        this.coordinateAllowace = coordinateAllowace;
    }
    
    @Column(name="ct_allowance")
    public Integer getCtAllowance() {
        return this.ctAllowance;
    }
    
    public void setCtAllowance(Integer ctAllowance) {
        this.ctAllowance = ctAllowance;
    }
    
    @Column(name="medical_allowance")
    public Integer getMedicalAllowance() {
        return this.medicalAllowance;
    }
    
    public void setMedicalAllowance(Integer medicalAllowance) {
        this.medicalAllowance = medicalAllowance;
    }
    
    @Column(name="five_year_allowance")
    public Integer getFiveYearAllowance() {
        return this.fiveYearAllowance;
    }
    
    public void setFiveYearAllowance(Integer fiveYearAllowance) {
        this.fiveYearAllowance = fiveYearAllowance;
    }

    @Column(name="staff_id")
    public String getStaffId() {
        return staffId;
    }

    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
        @Column(name="bank_account_no")
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }

    
    
    @Column(name="order_no")
    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="deleted")
    public Boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    
    
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empAccounts")
    public Set<EmpAccountAttachment> getEmpAccountAttachments() {
        return this.empAccountAttachments;
    }
    
    public void setEmpAccountAttachments(Set empAccountAttachments) {
        this.empAccountAttachments = empAccountAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empAccounts")
@OrderBy("id")    
public Set<Designation> getDesignations() {
        return this.designations;
    }
    
    public void setDesignations(Set designations) {
        this.designations = designations;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empAccounts")
    public Set<Salary> getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set salaries) {
        this.salaries = salaries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empAccounts")
    public Set<EmpCertificateIssue> getEmpCertificateIssues() {
        return this.empCertificateIssues;
    }
    
    public void setEmpCertificateIssues(Set empCertificateIssues) {
        this.empCertificateIssues = empCertificateIssues;
    }

  @Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }
}


