package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TgUser generated by hbm2java
 */
@Entity
@Table(name="tg_user"
    
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class TgUser  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private Boolean isDeleted;
     private String remarks;
     private Set<UserPrivilege> userPrivileges = new HashSet<UserPrivilege>(0);

    public TgUser() {
    }

	
    public TgUser(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public TgUser(String name, String password, Boolean isDeleted, String remarks, Set userPrivileges) {
       this.name = name;
       this.password = password;
       this.isDeleted = isDeleted;
       this.remarks = remarks;
       this.userPrivileges = userPrivileges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", unique=true, nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="password", nullable=false, length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tgUser")
    public Set<UserPrivilege> getUserPrivileges() {
        return this.userPrivileges;
    }
    
    public void setUserPrivileges(Set userPrivileges) {
        this.userPrivileges = userPrivileges;
    }


@Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }



}


