package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attendence generated by hbm2java
 */
@Entity
@Table(name="attendence")
public class Attendence  implements java.io.Serializable {


     private Integer attendenceId;
     private Months months;
     private StudentClassReg studentClassReg;
     private int totalDays;
     private int presentDays;
     private String remarks;

    public Attendence() {
    }

	
    public Attendence(Months months, StudentClassReg studentClassReg, int totalDays, int presentDays) {
        this.months = months;
        this.studentClassReg = studentClassReg;
        this.totalDays = totalDays;
        this.presentDays = presentDays;
    }
    public Attendence(Months months, StudentClassReg studentClassReg, int totalDays, int presentDays, String remarks) {
       this.months = months;
       this.studentClassReg = studentClassReg;
       this.totalDays = totalDays;
       this.presentDays = presentDays;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="attendence_id", unique=true, nullable=false)
    public Integer getAttendenceId() {
        return this.attendenceId;
    }
    
    public void setAttendenceId(Integer attendenceId) {
        this.attendenceId = attendenceId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id", nullable=false)
    public Months getMonths() {
        return this.months;
    }
    
    public void setMonths(Months months) {
        this.months = months;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_class_reg_id", nullable=false)
    public StudentClassReg getStudentClassReg() {
        return this.studentClassReg;
    }
    
    public void setStudentClassReg(StudentClassReg studentClassReg) {
        this.studentClassReg = studentClassReg;
    }
    
    @Column(name="total_days", nullable=false)
    public int getTotalDays() {
        return this.totalDays;
    }
    
    public void setTotalDays(int totalDays) {
        this.totalDays = totalDays;
    }
    
    @Column(name="present_days", nullable=false)
    public int getPresentDays() {
        return this.presentDays;
    }
    
    public void setPresentDays(int presentDays) {
        this.presentDays = presentDays;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return ""+presentDays; //To change body of generated methods, choose Tools | Templates.
    }


}


