package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name="classes"
   
)
public class Classes  implements java.io.Serializable {


     private Integer classId;
     private Section section;
     private String className;
     private Integer sequenceNo;
     private String remarks;
     private Set<Subjects> subjectses = new HashSet<Subjects>(0);
     private Set<StudentClassReg> studentClassRegs = new HashSet<StudentClassReg>(0);
     private Set<FeesStructure> feesStructures = new HashSet<FeesStructure>(0);

    public Classes() {
    }

	
    public Classes(Section section, String className) {
        this.section = section;
        this.className = className;
    }
    public Classes(Section section, String className, Integer sequenceNo, String remarks, Set subjectses, Set studentClassRegs, Set feesStructures) {
       this.section = section;
       this.className = className;
       this.sequenceNo = sequenceNo;
       this.remarks = remarks;
       this.subjectses = subjectses;
       this.studentClassRegs = studentClassRegs;
       this.feesStructures = feesStructures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="class_id", unique=true, nullable=false)
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="section_id", nullable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    
    @Column(name="class_name", nullable=false, length=100)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    
    @Column(name="sequence_no")
    public Integer getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="classes")
@OrderBy("sequenceNo")
    public Set<Subjects> getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set subjectses) {
        this.subjectses = subjectses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="classes")
    public Set<StudentClassReg> getStudentClassRegs() {
        return this.studentClassRegs;
    }
    
    public void setStudentClassRegs(Set studentClassRegs) {
        this.studentClassRegs = studentClassRegs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="classes")
    public Set<FeesStructure> getFeesStructures() {
        return this.feesStructures;
    }
    
    public void setFeesStructures(Set feesStructures) {
        this.feesStructures = feesStructures;
    }

    @Override
    public String toString() {
        return className; //To change body of generated methods, choose Tools | Templates.
    }


}


