package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name="designation")
public class Designation  implements java.io.Serializable {


     private Integer id;
     private EmpAccounts empAccounts;
     private Section section;
     private String name;
     private Date assignDate;
     private Date leaveDate;
     private String remarks;

    public Designation() {
    }

	
    public Designation(EmpAccounts empAccounts, Section section) {
        this.empAccounts = empAccounts;
        this.section = section;
    }
    public Designation(EmpAccounts empAccounts, Section section, String name, Date assignDate, Date leaveDate, String remarks) {
       this.empAccounts = empAccounts;
       this.section = section;
       this.name = name;
       this.assignDate = assignDate;
       this.leaveDate = leaveDate;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_accounts_id", nullable=false)
    public EmpAccounts getEmpAccounts() {
        return this.empAccounts;
    }
    
    public void setEmpAccounts(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="section_id", nullable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="assign_date", length=10)
    public Date getAssignDate() {
        return this.assignDate;
    }
    
    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="leave_date", length=10)
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


@Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }


}


