package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpAccountCategory generated by hbm2java
 */
@Entity
@Table(name="emp_account_category"
    
)
public class EmpAccountCategory  implements java.io.Serializable {


     private Integer empAccountCategoryId;
     private String name;
     private String remarks;
     private Set<EmpAccounts> empAccountses = new HashSet<EmpAccounts>(0);

    public EmpAccountCategory() {
    }

	
    public EmpAccountCategory(String name) {
        this.name = name;
    }
    public EmpAccountCategory(String name, String remarks, Set empAccountses) {
       this.name = name;
       this.remarks = remarks;
       this.empAccountses = empAccountses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="emp_account_category_id", unique=true, nullable=false)
    public Integer getEmpAccountCategoryId() {
        return this.empAccountCategoryId;
    }
    
    public void setEmpAccountCategoryId(Integer empAccountCategoryId) {
        this.empAccountCategoryId = empAccountCategoryId;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empAccountCategory")
    public Set<EmpAccounts> getEmpAccountses() {
        return this.empAccountses;
    }
    
    public void setEmpAccountses(Set empAccountses) {
        this.empAccountses = empAccountses;
    }


@Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }


}


