package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpCertificateIssue generated by hbm2java
 */
@Entity
@Table(name="emp_certificate_issue"
)
public class EmpCertificateIssue  implements java.io.Serializable {


     private Integer id;
     private EmpAccounts empAccounts;
     private String certificateName;
     private Date issueDate;
     private String remarks;

    public EmpCertificateIssue() {
    }

	
    public EmpCertificateIssue(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
    public EmpCertificateIssue(EmpAccounts empAccounts, String certificateName, Date issueDate, String remarks) {
       this.empAccounts = empAccounts;
       this.certificateName = certificateName;
       this.issueDate = issueDate;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_accounts_emp_accounts_id", nullable=false)
    public EmpAccounts getEmpAccounts() {
        return this.empAccounts;
    }
    
    public void setEmpAccounts(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
    
    @Column(name="certificate_name", length=100)
    public String getCertificateName() {
        return this.certificateName;
    }
    
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="issue_date", length=10)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


    @Override
    public String toString() {
        return certificateName; //To change body of generated methods, choose Tools | Templates.
    }


}


