package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name="exam_result"
)
public class ExamResult  implements java.io.Serializable {


     private Integer examResultId;
     private ExamType examType;
     private Subjects subjects;
     private StudentClassReg studentClassReg;
     private int obtainMarks;
     private Date examDate;
     private String remarks;

    public ExamResult() {
    }

	
    public ExamResult(ExamType examType, Subjects subjects, StudentClassReg studentClassReg, int obtainMarks) {
        this.examType = examType;
        this.subjects = subjects;
        this.studentClassReg = studentClassReg;
        this.obtainMarks = obtainMarks;
    }
    public ExamResult(ExamType examType, Subjects subjects, StudentClassReg studentClassReg, int obtainMarks, Date examDate, String remarks) {
       this.examType = examType;
       this.subjects = subjects;
       this.studentClassReg = studentClassReg;
       this.obtainMarks = obtainMarks;
       this.examDate = examDate;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="exam_result_id", unique=true, nullable=false)
    public Integer getExamResultId() {
        return this.examResultId;
    }
    
    public void setExamResultId(Integer examResultId) {
        this.examResultId = examResultId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_type_id", nullable=false)
    public ExamType getExamType() {
        return this.examType;
    }
    
    public void setExamType(ExamType examType) {
        this.examType = examType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject_id", nullable=false)
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_class_reg_id", nullable=false)
    public StudentClassReg getStudentClassReg() {
        return this.studentClassReg;
    }
    
    public void setStudentClassReg(StudentClassReg studentClassReg) {
        this.studentClassReg = studentClassReg;
    }
    
    @Column(name="obtain_marks", nullable=false)
    public int getObtainMarks() {
        return this.obtainMarks;
    }
    
    public void setObtainMarks(int obtainMarks) {
        this.obtainMarks = obtainMarks;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="exam_date", length=10)
    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@Override
    public String toString() {
        return com.school.constant.ConsSubject.getMarksStatus(obtainMarks); //To change body of generated methods, choose Tools | Templates.
    }



}


