package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExamType generated by hbm2java
 */
@Entity
@Table(name="exam_type"
)
public class ExamType  implements java.io.Serializable {


     private Integer examTypeId;
     private String examName;
     private Integer sequenceNo;
     private String remarks;
     private Set<ExamResult> examResults = new HashSet<ExamResult>(0);

    public ExamType() {
    }

	
    public ExamType(String examName) {
        this.examName = examName;
    }
    public ExamType(String examName, Integer sequenceNo, String remarks, Set examResults) {
       this.examName = examName;
       this.sequenceNo = sequenceNo;
       this.remarks = remarks;
       this.examResults = examResults;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="exam_type_id", unique=true, nullable=false)
    public Integer getExamTypeId() {
        return this.examTypeId;
    }
    
    public void setExamTypeId(Integer examTypeId) {
        this.examTypeId = examTypeId;
    }
    
    @Column(name="exam_name", nullable=false, length=100)
    public String getExamName() {
        return this.examName;
    }
    
    public void setExamName(String examName) {
        this.examName = examName;
    }
    
    @Column(name="sequence_no")
    public Integer getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="examType")
    public Set<ExamResult> getExamResults() {
        return this.examResults;
    }
    
    public void setExamResults(Set examResults) {
        this.examResults = examResults;
    }

@Override
    public String toString() {
        return examName; //To change body of generated methods, choose Tools | Templates.
    }


}


