package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="module")
public class Module  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String remarks;
     private Set<UserPrivilege> userPrivileges = new HashSet<UserPrivilege>(0);

    public Module() {
    }

	
    public Module(String name) {
        this.name = name;
    }
    public Module(String name, String remarks, Set userPrivileges) {
       this.name = name;
       this.remarks = remarks;
       this.userPrivileges = userPrivileges;
    }
    
    public Module(String name, String remarks) {
       this.name = name;
       this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false, length=11)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
   
    
    
    @Column(name="name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="module")
    public Set<UserPrivilege> getUserPrivileges() {
        return this.userPrivileges;
    }
    
    public void setUserPrivileges(Set userPrivileges) {
        this.userPrivileges = userPrivileges;
    }


 @Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }


}


