package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name="salary"
    
)
public class Salary  implements java.io.Serializable {


     private Integer salaryId;
     private EmpAccounts empAccounts;
     private Months months;
     private Integer amount;
     private String remarks;
     private Integer deposit;
     private Integer casualLeave;
     private Integer warning;
     private Integer late;
     private Integer wentEarly;
     private Integer other;
     private Integer bonus;
     private String depositRemarls;
     private String casualLeaveRemarks;
     private String warningRemarks;
     private String lateRemarks;
     private String wentEarlyRemarks;
     private String otherRemarks;
     private String bonusRemarks;
     private Integer basicSalary;
     private Integer travellingAllowance;
     private Integer otherAllowance;
     private Integer coordinateAllowace;
     private Integer fiveYearAllowance;
     private Integer medicalAllowance;
     private Integer ctAllowance;
     private Integer headAllowance;
     private Integer workingDays;

    public Salary() {
    }

	
    public Salary(EmpAccounts empAccounts, Months months) {
        this.empAccounts = empAccounts;
        this.months = months;
    }
    public Salary(EmpAccounts empAccounts, Months months, Integer amount, String remarks, Integer deposit, Integer casualLeave, Integer warning, Integer late, Integer wentEarly, Integer other, Integer bonus, String depositRemarls, String casualLeaveRemarks, String warningRemarks, String lateRemarks, String wentEarlyRemarks, String otherRemarks, String bonusRemarks, Integer basicSalary, Integer travellingAllowance, Integer otherAllowance, Integer coordinateAllowace, Integer fiveYearAllowance, Integer medicalAllowance, Integer ctAllowance, Integer headAllowance, Integer workingDays) {
       this.empAccounts = empAccounts;
       this.months = months;
       this.amount = amount;
       this.remarks = remarks;
       this.deposit = deposit;
       this.casualLeave = casualLeave;
       this.warning = warning;
       this.late = late;
       this.wentEarly = wentEarly;
       this.other = other;
       this.bonus = bonus;
       this.depositRemarls = depositRemarls;
       this.casualLeaveRemarks = casualLeaveRemarks;
       this.warningRemarks = warningRemarks;
       this.lateRemarks = lateRemarks;
       this.wentEarlyRemarks = wentEarlyRemarks;
       this.otherRemarks = otherRemarks;
       this.bonusRemarks = bonusRemarks;
       this.basicSalary = basicSalary;
       this.travellingAllowance = travellingAllowance;
       this.otherAllowance = otherAllowance;
       this.coordinateAllowace = coordinateAllowace;
       this.fiveYearAllowance = fiveYearAllowance;
       this.medicalAllowance = medicalAllowance;
       this.ctAllowance = ctAllowance;
       this.headAllowance = headAllowance;
       this.workingDays = workingDays;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="salary_id", unique=true, nullable=false)
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_accounts_id", nullable=false)
    public EmpAccounts getEmpAccounts() {
        return this.empAccounts;
    }
    
    public void setEmpAccounts(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id", nullable=false)
    public Months getMonths() {
        return this.months;
    }
    
    public void setMonths(Months months) {
        this.months = months;
    }
    
    @Column(name="amount")
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="deposit")
    public Integer getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }
    
    @Column(name="casual_leave")
    public Integer getCasualLeave() {
        return this.casualLeave;
    }
    
    public void setCasualLeave(Integer casualLeave) {
        this.casualLeave = casualLeave;
    }
    
    @Column(name="warning")
    public Integer getWarning() {
        return this.warning;
    }
    
    public void setWarning(Integer warning) {
        this.warning = warning;
    }
    
    @Column(name="late")
    public Integer getLate() {
        return this.late;
    }
    
    public void setLate(Integer late) {
        this.late = late;
    }
    
    @Column(name="went_early")
    public Integer getWentEarly() {
        return this.wentEarly;
    }
    
    public void setWentEarly(Integer wentEarly) {
        this.wentEarly = wentEarly;
    }
    
    @Column(name="other")
    public Integer getOther() {
        return this.other;
    }
    
    public void setOther(Integer other) {
        this.other = other;
    }
    
    @Column(name="bonus")
    public Integer getBonus() {
        return this.bonus;
    }
    
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }
    
    @Column(name="deposit_remarls", length=100)
    public String getDepositRemarls() {
        return this.depositRemarls;
    }
    
    public void setDepositRemarls(String depositRemarls) {
        this.depositRemarls = depositRemarls;
    }
    
    @Column(name="casual_leave_remarks", length=100)
    public String getCasualLeaveRemarks() {
        return this.casualLeaveRemarks;
    }
    
    public void setCasualLeaveRemarks(String casualLeaveRemarks) {
        this.casualLeaveRemarks = casualLeaveRemarks;
    }
    
    @Column(name="warning_remarks", length=100)
    public String getWarningRemarks() {
        return this.warningRemarks;
    }
    
    public void setWarningRemarks(String warningRemarks) {
        this.warningRemarks = warningRemarks;
    }
    
    @Column(name="late_remarks", length=100)
    public String getLateRemarks() {
        return this.lateRemarks;
    }
    
    public void setLateRemarks(String lateRemarks) {
        this.lateRemarks = lateRemarks;
    }
    
    @Column(name="went_early_remarks", length=100)
    public String getWentEarlyRemarks() {
        return this.wentEarlyRemarks;
    }
    
    public void setWentEarlyRemarks(String wentEarlyRemarks) {
        this.wentEarlyRemarks = wentEarlyRemarks;
    }
    
    @Column(name="other_remarks", length=100)
    public String getOtherRemarks() {
        return this.otherRemarks;
    }
    
    public void setOtherRemarks(String otherRemarks) {
        this.otherRemarks = otherRemarks;
    }
    
    @Column(name="bonus_remarks", length=100)
    public String getBonusRemarks() {
        return this.bonusRemarks;
    }
    
    public void setBonusRemarks(String bonusRemarks) {
        this.bonusRemarks = bonusRemarks;
    }
    
    @Column(name="basic_salary")
    public Integer getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(Integer basicSalary) {
        this.basicSalary = basicSalary;
    }
    
    @Column(name="travelling_allowance")
    public Integer getTravellingAllowance() {
        return this.travellingAllowance;
    }
    
    public void setTravellingAllowance(Integer travellingAllowance) {
        this.travellingAllowance = travellingAllowance;
    }
    
    @Column(name="other_allowance")
    public Integer getOtherAllowance() {
        return this.otherAllowance;
    }
    
    public void setOtherAllowance(Integer otherAllowance) {
        this.otherAllowance = otherAllowance;
    }
    
    @Column(name="coordinate_allowace")
    public Integer getCoordinateAllowace() {
        return this.coordinateAllowace;
    }
    
    public void setCoordinateAllowace(Integer coordinateAllowace) {
        this.coordinateAllowace = coordinateAllowace;
    }
    
    @Column(name="five_year_allowance")
    public Integer getFiveYearAllowance() {
        return this.fiveYearAllowance;
    }
    
    public void setFiveYearAllowance(Integer fiveYearAllowance) {
        this.fiveYearAllowance = fiveYearAllowance;
    }
    
    @Column(name="medical_allowance")
    public Integer getMedicalAllowance() {
        return this.medicalAllowance;
    }
    
    public void setMedicalAllowance(Integer medicalAllowance) {
        this.medicalAllowance = medicalAllowance;
    }
    
    @Column(name="ct_allowance")
    public Integer getCtAllowance() {
        return this.ctAllowance;
    }
    
    public void setCtAllowance(Integer ctAllowance) {
        this.ctAllowance = ctAllowance;
    }
    
    @Column(name="head_allowance")
    public Integer getHeadAllowance() {
        return this.headAllowance;
    }
    
    public void setHeadAllowance(Integer headAllowance) {
        this.headAllowance = headAllowance;
    }
    
    @Column(name="working_days")
    public Integer getWorkingDays() {
        return this.workingDays;
    }
    
    public void setWorkingDays(Integer workingDays) {
        this.workingDays = workingDays;
    }




}


