package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SchoolConfig generated by hbm2java
 */
@Entity
@Table(name="school_config"
)
public class SchoolConfig  implements java.io.Serializable {


     private String keyName;
     private String valueName;
     private String remarks;

    public SchoolConfig() {
    }

	
    public SchoolConfig(String keyName, String valueName) {
        this.keyName = keyName;
        this.valueName = valueName;
    }
    public SchoolConfig(String keyName, String valueName, String remarks) {
       this.keyName = keyName;
       this.valueName = valueName;
       this.remarks = remarks;
    }
   
     @Id 
    
    @Column(name="key_name", unique=true, nullable=false, length=200)
    public String getKeyName() {
        return this.keyName;
    }
    
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }
    
    @Column(name="value_name", nullable=false, length=500)
    public String getValueName() {
        return this.valueName;
    }
    
    public void setValueName(String valueName) {
        this.valueName = valueName;
    }
    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


