package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * StudentClassReg generated by hbm2java
 */
@Entity
@Table(name="student_class_reg"
    
)
public class StudentClassReg  implements java.io.Serializable {


     private Integer studentClassRegId;
     private Campus campus;
     private Student student;
     private Classes classes;
     private Years years;
     private int isLeaved;
     private String remarks;
     private Set<Fees> feeses = new HashSet<Fees>(0);
     private Set<Attendence> attendences = new HashSet<Attendence>(0);
     private Set<ExamResult> examResults = new HashSet<ExamResult>(0);

    public StudentClassReg() {
    }

	
    public StudentClassReg(Campus campus, Student student, Classes classes, Years years, int isLeaved, String remarks) {
        this.campus = campus;
        this.student = student;
        this.classes = classes;
        this.years = years;
        this.isLeaved = isLeaved;
        this.remarks = remarks;
    }
    public StudentClassReg(Campus campus, Student student, Classes classes, Years years, int isLeaved, String remarks, Set feeses, Set attendences, Set examResults) {
       this.campus = campus;
       this.student = student;
       this.classes = classes;
       this.years = years;
       this.isLeaved = isLeaved;
       this.remarks = remarks;
       this.feeses = feeses;
       this.attendences = attendences;
       this.examResults = examResults;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="student_class_reg_id", unique=true, nullable=false)
    public Integer getStudentClassRegId() {
        return this.studentClassRegId;
    }
    
    public void setStudentClassRegId(Integer studentClassRegId) {
        this.studentClassRegId = studentClassRegId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campus_id", nullable=false)
    public Campus getCampus() {
        return this.campus;
    }
    
    public void setCampus(Campus campus) {
        this.campus = campus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="class_id", nullable=false)
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="year_id", nullable=false)
    public Years getYears() {
        return this.years;
    }
    
    public void setYears(Years years) {
        this.years = years;
    }
    
    @Column(name="is_leaved", nullable=false)
    public int getIsLeaved() {
        return this.isLeaved;
    }
    
    public void setIsLeaved(int isLeaved) {
        this.isLeaved = isLeaved;
    }
    
    @Column(name="remarks", nullable=false, length=50)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentClassReg")
    public Set<Fees> getFeeses() {
        return this.feeses;
    }
    
    public void setFeeses(Set feeses) {
        this.feeses = feeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentClassReg")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set attendences) {
        this.attendences = attendences;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentClassReg")
@OrderBy("examResultId")    
public Set<ExamResult> getExamResults() {
        return this.examResults;
    }
    
    public void setExamResults(Set examResults) {
        this.examResults = examResults;
    }


@Override
    public String toString() {
        return classes.getClassName(); //To change body of generated methods, choose Tools | Templates.
    }


}


