package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Years generated by hbm2java
 */
@Entity
@Table(name="years"
    
    , uniqueConstraints = @UniqueConstraint(columnNames="year_name") 
)
public class Years  implements java.io.Serializable {


     private Integer yearId;
     private int yearName;
     private String remarks;
     private Set<StudentClassReg> studentClassRegs = new HashSet<StudentClassReg>(0);
     private Set<Event> events = new HashSet<Event>(0);
     private Set<Months> monthses = new HashSet<Months>(0);

    public Years() {
    }

	
    public Years(int yearName) {
        this.yearName = yearName;
    }
    public Years(int yearName, String remarks, Set studentClassRegs, Set events, Set monthses) {
       this.yearName = yearName;
       this.remarks = remarks;
       this.studentClassRegs = studentClassRegs;
       this.events = events;
       this.monthses = monthses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="year_id", unique=true, nullable=false)
    public Integer getYearId() {
        return this.yearId;
    }
    
    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }
    
    @Column(name="year_name", unique=true, nullable=false)
    public int getYearName() {
        return this.yearName;
    }
    
    public void setYearName(int yearName) {
        this.yearName = yearName;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="years")
    public Set<StudentClassReg> getStudentClassRegs() {
        return this.studentClassRegs;
    }
    
    public void setStudentClassRegs(Set studentClassRegs) {
        this.studentClassRegs = studentClassRegs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="years")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="years")
@OrderBy("monthId")
    public Set<Months> getMonthses() {
        return this.monthses;
    }
    
    public void setMonthses(Set monthses) {
        this.monthses = monthses;
    }



@Override
    public String toString() {
        return ""+yearName; //To change body of generated methods, choose Tools | Templates.
    }


}


