package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Months generated by hbm2java
 */
@Entity
@Table(name="months")
public class Months  implements java.io.Serializable {


     private Integer monthId;
     private Years years;
     private String monthName;
     private Date monthDate;
     private String remarks;
     private Set<Salary> salaries = new HashSet<Salary>(0);
     private Set<Fees> feeses = new HashSet<Fees>(0);
     private Set<Attendence> attendences = new HashSet<Attendence>(0);

    public Months() {
    }

	
    public Months(Years years, String monthName) {
        this.years = years;
        this.monthName = monthName;
    }
    public Months(Years years, String monthName, Date monthDate, String remarks, Set salaries, Set feeses, Set attendences) {
       this.years = years;
       this.monthName = monthName;
       this.monthDate = monthDate;
       this.remarks = remarks;
       this.salaries = salaries;
       this.feeses = feeses;
       this.attendences = attendences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="month_id", unique=true, nullable=false)
    public Integer getMonthId() {
        return this.monthId;
    }
    
    public void setMonthId(Integer monthId) {
        this.monthId = monthId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="year_id", nullable=false)
    public Years getYears() {
        return this.years;
    }
    
    public void setYears(Years years) {
        this.years = years;
    }
    
    @Column(name="month_name", nullable=false, length=11)
    public String getMonthName() {
        return this.monthName;
    }
    
    public void setMonthName(String monthName) {
        this.monthName = monthName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="month_date", length=10)
    public Date getMonthDate() {
        return this.monthDate;
    }
    
    public void setMonthDate(Date monthDate) {
        this.monthDate = monthDate;
    }
    
    @Column(name="remarks", length=50)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="months")
    public Set<Salary> getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set salaries) {
        this.salaries = salaries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="months")
    public Set<Fees> getFeeses() {
        return this.feeses;
    }
    
    public void setFeeses(Set feeses) {
        this.feeses = feeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="months")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set attendences) {
        this.attendences = attendences;
    }

    @Override
    public String toString() {
        return monthName; //To change body of generated methods, choose Tools | Templates.
    }



}


