package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FeesStructure generated by hbm2java
 */
@Entity
@Table(name="fees_structure"
)
public class FeesStructure  implements java.io.Serializable {


     private Integer feesStructureId;
     private Campus campus;
     private Classes classes;
     private int amount;
     private String remarks;

    public FeesStructure() {
    }

	
    public FeesStructure(Campus campus, Classes classes, int amount) {
        this.campus = campus;
        this.classes = classes;
        this.amount = amount;
    }
    public FeesStructure(Campus campus, Classes classes, int amount, String remarks) {
       this.campus = campus;
       this.classes = classes;
       this.amount = amount;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="fees_structure_id", unique=true, nullable=false)
    public Integer getFeesStructureId() {
        return this.feesStructureId;
    }
    
    public void setFeesStructureId(Integer feesStructureId) {
        this.feesStructureId = feesStructureId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campus_id", nullable=false)
    public Campus getCampus() {
        return this.campus;
    }
    
    public void setCampus(Campus campus) {
        this.campus = campus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


