package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpAccountAttachment generated by hbm2java
 */
@Entity
@Table(name="emp_account_attachment"
    
)
public class EmpAccountAttachment  implements java.io.Serializable {


     private Integer empAccountAttachmentId;
     private EmpAccounts empAccounts;
     private String attachName;
     private byte[] attachement;
     private String remarks;

    public EmpAccountAttachment() {
    }

	
    public EmpAccountAttachment(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
    public EmpAccountAttachment(EmpAccounts empAccounts, String attachName, byte[] attachement, String remarks) {
       this.empAccounts = empAccounts;
       this.attachName = attachName;
       this.attachement = attachement;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="emp_account_attachment_id", unique=true, nullable=false)
    public Integer getEmpAccountAttachmentId() {
        return this.empAccountAttachmentId;
    }
    
    public void setEmpAccountAttachmentId(Integer empAccountAttachmentId) {
        this.empAccountAttachmentId = empAccountAttachmentId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_accounts_id", nullable=false)
    public EmpAccounts getEmpAccounts() {
        return this.empAccounts;
    }
    
    public void setEmpAccounts(EmpAccounts empAccounts) {
        this.empAccounts = empAccounts;
    }
    
    @Column(name="attach_name", length=100)
    public String getAttachName() {
        return this.attachName;
    }
    
    public void setAttachName(String attachName) {
        this.attachName = attachName;
    }
    
    @Column(name="attachement")
    public byte[] getAttachement() {
        return this.attachement;
    }
    
    public void setAttachement(byte[] attachement) {
        this.attachement = attachement;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@Override
    public String toString() {
        return remarks; //To change body of generated methods, choose Tools | Templates.
    }


}


