package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
)
public class Event  implements java.io.Serializable {


     private Integer id;
     private Years years;
     private String desciption;
     private Date day;
     private Set<Awards> awardses = new HashSet<Awards>(0);

    public Event() {
    }

	
    public Event(Years years) {
        this.years = years;
    }
    public Event(Years years, String desciption, Date day, Set awardses) {
       this.years = years;
       this.desciption = desciption;
       this.day = day;
       this.awardses = awardses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="year_id", nullable=false)
    public Years getYears() {
        return this.years;
    }
    
    public void setYears(Years years) {
        this.years = years;
    }
    
    @Column(name="desciption", length=200)
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="day", length=10)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="event")
    public Set<Awards> getAwardses() {
        return this.awardses;
    }
    
    public void setAwardses(Set awardses) {
        this.awardses = awardses;
    }


    @Override
    public String toString() {
        return desciption; //To change body of generated methods, choose Tools | Templates.
    }


}


