package com.school.model;
// Generated Dec 9, 2014 7:01:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade")
public class Grade  implements java.io.Serializable {


     private Integer gradeId;
     private String name;
     private float percMin;
     private float percMax;
     private String remarks;

    public Grade() {
    }

	
    public Grade(String name, float percMin, float percMax) {
        this.name = name;
        this.percMin = percMin;
        this.percMax = percMax;
    }
    public Grade(String name, float percMin, float percMax, String remarks) {
       this.name = name;
       this.percMin = percMin;
       this.percMax = percMax;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="grade_id", unique=true, nullable=false)
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
    
    @Column(name="name", nullable=false, length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="perc_min", nullable=false, precision=12, scale=0)
    public float getPercMin() {
        return this.percMin;
    }
    
    public void setPercMin(float percMin) {
        this.percMin = percMin;
    }
    
    @Column(name="perc_max", nullable=false, precision=12, scale=0)
    public float getPercMax() {
        return this.percMax;
    }
    
    public void setPercMax(float percMax) {
        this.percMax = percMax;
    }
    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


